version: '3'
services:
  servers:
    build: .
    ports:
      - "5000-5007:5000-5007"
    restart: unless-stopped
  frontend:
    build: frontend/
    ports:
      - "80:80"
    restart: unless-stopped
